debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fsocity?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  config: classpath:logback-spring-dev.xml # 日志配置文件
