server:
  port: 9090

spring:
  application:
    name: fsocity
  datasource:
    url: jdbc:mysql://localhost:3306/fsocity?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # driver-class需要注意mysql驱动的版本(com.mysql.cj.jdbc.Driver 或 com.mysql.jdbc.Driver)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid的其他属性配置
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
      validation-query: select 'x'
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 置监控统计拦截的filters，去掉后监控界面sql无法统计，stat: 监控统计、Slf4j:日志记录、waLL: 防御sqL注入
      filters: stat,wall,slf4j
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        # 是否启用StatFilter默认值true
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        # 是否启用StatViewServlet默认值true
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台，默认为root
        login-username: druid
        login-password: druid
        # IP白名单
        allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        deny:
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  thymeleaf:
    cache: false # 取消页面cache

mybatis-plus:
  # 去@MapperScan注解改
  # mapper-scan-locations: com.fsocity.modules.*.mapper
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      column-format: '`%s`' # 字段格式化。用于解决字段名使用mysql关键字的问题。
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

fsocity:
  swagger:
    api-base-package: com.fsocity.modules
    title: Fsocity 脚手架
    description: 接口文档
    contact-name: Zail
    version: 1.0.0
    enable-security: true
  security:
    csrf: # 关闭csrf
      enable: false
    cors: # 关闭cors
      enable: false
    admin:
      enable: true
      authenticated-urls: # 需要安全认证的地址
        - /admin
        - /admin/**
      unauthenticated-urls: # 安全路径白名单
        - /admin/login
        - /admin/logout
        - /admin/authenticationRequire
        - /admin/accessDenied
        - /admin/validationCode/**
      require-authentication-url: /admin/authenticationRequire
      login-page: /admin/login
      login-processing-url: /admin/login
      logout-url: /admin/logout
      login-success-url: /admin/index
      access-denied-url: /admin/accessDenied
      validation-code:
        type: image
      remember-me-name: rememberMe
      remember-me-seconds: 7200
      jwt:
        enable: true
        http-header-name: Authorization #JWT存储的请求头
        secret: mall-admin-secret #JWT加解密使用的密钥
        expiration: 604800 #JWT的超期限时间(60*60*24*7)
        token-head: 'Bearer '  #JWT负载中拿到开头
    
